version: '3'

volumes:
    mysql_data:
        driver: local

services:
    webserver:
        container_name: webserver
        build: ./webserver
        ports:
            - "80:80"
        depends_on: 
            - webapp
        volumes:
            - ./logs/webserver:/var/log/nginx:cached
            - ./webapp:/var/www/webapp:cached
        networks:
        - local

    database:
        container_name: database
        image: mysql:5.7
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: database
            MYSQL_PASSWORD: database
        networks:
        - local

    webapp:
        container_name: webapp
        build: 
            context: ./webapp-dockerfile
            args: 
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        ports:
            - "9000:9001"
        environment: 
            DATABASE_URL: "mysql://database:database@database/database?encoding=utf8&timezone=UTC&cacheMetadata=true&quoteIdentifiers=false&persistent=false"
            APP_NAME: "Cake"
            DEBUG: "true"
            APP_ENCODING: "UTF-8"
            APP_DEFAULT_LOCALE: "en_US"
            APP_DEFAULT_TIMEZONE: "UTC"
            SECURITY_SALT: "rI995u8dVwv3cs88Bd44ufdpo9wOqhAeChkKEt95t92JvqSpZ2HadCCrI339UlNw"
            EMAIL_TRANSPORT_DEFAULT_URL: "smtp://maildev:25"
        volumes:
            - ./webapp:/var/www/webapp:cached
            - ./logs/webapp:/var/www/webapp/var/log:cached
        depends_on: 
            - database
        networks:
        - local

    maildev:
        image: maildev/maildev
        ports:
        - "1080:1080"
        networks:
        - local
networks:
    local: